// Import necessary dependencies from Next.js
import type { Metadata } from "next";
// Import font families from Google Fonts through Next.js font system
import { Geist, Geist_Mono } from "next/font/google";
// Import global CSS styles
import "./globals.css";

// Configure the Geist Sans font family
// This is a modern, clean sans-serif font for general text
const geistSans = Geist({
  variable: "--font-geist-sans", // Creates a CSS variable for the font
  subsets: ["latin"], // Only loads Latin character set for better performance
});

// Configure the Geist Mono font family
// This is a monospace font, typically used for code snippets
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // Creates a CSS variable for the font
  subsets: ["latin"], // Only loads Latin character set for better performance
});

// Define metadata for the application
// This information appears in browser tabs and search results
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component that wraps all pages
// This is a special Next.js component that provides the basic HTML structure
export default function RootLayout({
  children, // Children represents all the page content that will be wrapped by this layout
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Basic HTML structure with language set to English
    <html lang="en">
      <body
        // Apply font variables and antialiasing for smoother text rendering
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children} {/* Render the page content */}
      </body>
    </html>
  );
}
